version: '3.8'

services:
  postgres:
    image: postgres:16.4-alpine
    container_name: binance_postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: binancebot_user
      POSTGRES_PASSWORD: binancebot_password
      POSTGRES_DB: binancebot_app
    volumes:
      - binance_postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  binance_postgres_data:
