name: Pull Request Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run unit tests
        run: mvn test
